using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using Aspire.Hosting.Coolify;

namespace Aspire.Hosting.Coolify.Tests;

/// <summary>
/// TC-015 exit criteria for FT-011 — TypeScript AppHost parity. Asserts the generator hook's
/// emitted module honours the public contract, the pure-recording-shim discipline, per-function
/// idempotency, null/undefined runtime backstop, credentials-tuple shape enforcement,
/// byte-stability, no-new-error-symbols, and the no-TS-side-reimplementation prohibition.
/// </summary>
public class TypeScriptAppHostParityExitCriteriaTests
{
    private static string Source => TypeScriptAppHostGenerator.GetModuleSource();

    // ---- A. aspire restore emits the module ---------------------------------------------

    [Fact]
    public void A1_Header_IsFirstLine()
    {
        var src = Source;
        var firstLine = src.Split('\n', 2)[0];
        Assert.Equal("// auto-generated by aspire restore; do not edit", firstLine);
    }

    [Fact]
    public void A1_EmitTo_WritesExactlyOneFile_InDesignatedDirectory()
    {
        var tmp = Path.Combine(Path.GetTempPath(), "ft011-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tmp);
        try
        {
            var before = SnapshotTree(tmp);
            var path = TypeScriptAppHostGenerator.EmitTo(tmp);
            var after = SnapshotTree(tmp);

            var created = after.Except(before).ToList();
            // Exactly one new file (the module). The aspire.generated directory is allowed
            // as a created-by-side-effect path, but no other files outside it.
            var newFiles = created.Where(p => File.Exists(p)).ToList();
            Assert.Single(newFiles);
            Assert.Equal(path, newFiles[0]);

            // I-10: nothing written outside the designated directory.
            var generatedDir = Path.Combine(tmp, TypeScriptAppHostGenerator.GeneratedDirectoryName);
            Assert.StartsWith(generatedDir + Path.DirectorySeparatorChar, path);
        }
        finally
        {
            Directory.Delete(tmp, recursive: true);
        }
    }

    private static List<string> SnapshotTree(string root)
        => Directory.EnumerateFileSystemEntries(root, "*", SearchOption.AllDirectories).ToList();

    // ---- B. Public contract — exactly four named exports --------------------------------

    [Fact]
    public void B3_ExportsExactlyFourNamedFunctions()
    {
        var src = Source;
        var matches = Regex.Matches(src, @"^export function (\w+)\s*\(", RegexOptions.Multiline);
        var names = matches.Select(m => m.Groups[1].Value).ToHashSet();
        Assert.Equal(
            new HashSet<string> { "withCoolifyDeploy", "withImageRegistry", "withCoolifyDestination", "withManagedDashboard" },
            names);
    }

    [Fact]
    public void B4_NoDefaultExport()
    {
        Assert.DoesNotMatch(new Regex(@"\bexport\s+default\b"), Source);
    }

    [Fact]
    public void B5_Signatures_Match_FT011_Behaviour()
    {
        var src = Source;
        // withCoolifyDeploy(builder, url, token) — all required, parameter-handle-typed.
        Assert.Matches(
            new Regex(@"export function withCoolifyDeploy\(\s*builder: IDistributedApplicationBuilder,\s*url: IResourceHandle<ParameterResource>,\s*token: IResourceHandle<ParameterResource>,\s*\): IDistributedApplicationBuilder"),
            src);

        // withImageRegistry(builder, prefix, credentials?) — credentials optional 2-tuple.
        Assert.Matches(
            new Regex(@"export function withImageRegistry\(\s*builder: IDistributedApplicationBuilder,\s*prefix: IResourceHandle<ParameterResource>,\s*credentials\?: \[IResourceHandle<ParameterResource>, IResourceHandle<ParameterResource>\],\s*\): IDistributedApplicationBuilder"),
            src);

        // withCoolifyDestination(builder, name).
        Assert.Matches(
            new Regex(@"export function withCoolifyDestination\(\s*builder: IDistributedApplicationBuilder,\s*name: IResourceHandle<ParameterResource>,\s*\): IDistributedApplicationBuilder"),
            src);

        // withManagedDashboard(builder, dashboardToken).
        Assert.Matches(
            new Regex(@"export function withManagedDashboard\(\s*builder: IDistributedApplicationBuilder,\s*dashboardToken: IResourceHandle<ParameterResource>,\s*\): IDistributedApplicationBuilder"),
            src);
    }

    // ---- C. Pure recording shim ---------------------------------------------------------

    [Fact]
    public void C6_NoHttpOrChildProcessOrDockerOrImageTagOrPhaseLiterals()
    {
        var src = Source;
        Assert.DoesNotContain("fetch(", src);
        Assert.DoesNotContain("import(\"http", src);
        Assert.DoesNotContain("import('http", src);
        Assert.DoesNotContain("child_process", src);
        Assert.DoesNotContain("docker", src);
        Assert.DoesNotContain(":latest", src);
        // No phase-name string literals (must not appear as quoted strings).
        foreach (var phase in new[] { "configure", "build", "push", "deploy", "verify" })
        {
            Assert.DoesNotContain("\"" + phase + "\"", src);
            Assert.DoesNotContain("'" + phase + "'", src);
        }
    }

    [Fact]
    public void C6_FunctionBodies_ContainOnly_ValidationAndSlotWrites()
    {
        // No value-reading APIs are invoked anywhere in the module. The handle type exposes
        // only `name` / `resource`; reading a parameter value would require a method call like
        // `.getValue()`, `.value(`, `await resolve(`, etc.
        var src = Source;
        Assert.DoesNotMatch(new Regex(@"\.\s*getValue\s*\("), src);
        Assert.DoesNotMatch(new Regex(@"\.\s*resolveValue\s*\("), src);
        Assert.DoesNotMatch(new Regex(@"\bawait\b"), src);
    }

    // ---- E. Per-function idempotency rules ---------------------------------------------

    [Fact]
    public void E8_WithCoolifyDeploy_IsFirstCallWins()
    {
        var body = ExtractFunctionBody(Source, "withCoolifyDeploy");
        Assert.Matches(new Regex(@"if \(slots\.deployPair !== undefined\)\s*\{\s*return builder"), body);
    }

    [Fact]
    public void E9_E10_E11_OtherThree_AreLastCallWins()
    {
        var src = Source;
        // No "first-call-wins" early return guarding the slot in the other three functions.
        var registry = ExtractFunctionBody(src, "withImageRegistry");
        Assert.DoesNotMatch(new Regex(@"if \(slots\.registryPrefix !== undefined\)\s*\{\s*return"), registry);

        var dest = ExtractFunctionBody(src, "withCoolifyDestination");
        Assert.DoesNotMatch(new Regex(@"if \(slots\.destinationName !== undefined\)\s*\{\s*return"), dest);

        var dash = ExtractFunctionBody(src, "withManagedDashboard");
        Assert.DoesNotMatch(new Regex(@"if \(slots\.dashboardToken !== undefined\)\s*\{\s*return"), dash);

        // FT-010 I-5: opt-in flag is set to true unconditionally in the dashboard shim.
        Assert.Contains("slots.dashboardOptedIn = true;", dash);
    }

    // ---- F. No handle value read --------------------------------------------------------

    [Fact]
    public void F12_NoSentinelLeakOpportunity_NoHandleValueRead()
    {
        // The shim never invokes a value-reading API on the handle type. The only allowed
        // operations are typeof / instance-of / direct slot capture. This includes the
        // documented sentinel `SENTINEL_TS_TOKEN_DO_NOT_LEAK_011` — it must never appear in
        // the emitted module, and there must be no path that could compute or log a handle
        // value (covered by C6_FunctionBodies above).
        var src = Source;
        Assert.DoesNotContain("SENTINEL", src);
    }

    // ---- G. Runtime backstop on null / undefined ----------------------------------------

    [Fact]
    public void G13_RuntimeBackstop_NamesArgumentAndPointsAtCSharpFeature()
    {
        var src = Source;
        // Each shim throws Error with argument-naming, See FT-XXX message for required args.
        Assert.Contains("withCoolifyDeploy: 'builder' argument must be an IDistributedApplicationBuilder", src);
        Assert.Contains("withCoolifyDeploy: 'url' argument must be a parameter handle", src);
        Assert.Contains("withCoolifyDeploy: 'token' argument must be a parameter handle", src);
        Assert.Contains("See FT-001.", src);

        Assert.Contains("withImageRegistry: 'prefix' argument must be a parameter handle", src);
        Assert.Contains("See FT-003.", src);

        Assert.Contains("withCoolifyDestination: 'name' argument must be a parameter handle", src);
        Assert.Contains("See FT-005.", src);

        Assert.Contains("withManagedDashboard: 'dashboardToken' argument must be a parameter handle", src);
        Assert.Contains("See FT-010.", src);
    }

    // ---- H. credentials tuple shape enforcement ----------------------------------------

    [Fact]
    public void H14_WithImageRegistry_RejectsNullInsideCredentialsTuple()
    {
        var body = ExtractFunctionBody(Source, "withImageRegistry");
        Assert.Contains("'credentials[0]' (username)", body);
        Assert.Contains("'credentials[1]' (password)", body);
        Assert.Matches(new Regex(@"if \(credentials\[0\] === null \|\| credentials\[0\] === undefined\)"), body);
        Assert.Matches(new Regex(@"if \(credentials\[1\] === null \|\| credentials\[1\] === undefined\)"), body);
    }

    [Fact]
    public void H15_CredentialsTuple_IsTypedAsExactlyTwoElement()
    {
        // The TS type signature declares a 2-tuple, not `Array<...>` or `[...]` of arbitrary
        // length — this is what gives compile-time rejection of a one-element tuple.
        Assert.Matches(
            new Regex(@"credentials\?: \[IResourceHandle<ParameterResource>, IResourceHandle<ParameterResource>\]"),
            Source);
    }

    // ---- I. Byte-stable emitted file ----------------------------------------------------

    [Fact]
    public void I16_ModuleSource_IsByteStableAcrossInvocations()
    {
        var a = TypeScriptAppHostGenerator.GetModuleSource();
        var b = TypeScriptAppHostGenerator.GetModuleSource();
        Assert.Equal(Sha256(a), Sha256(b));

        var tmp = Path.Combine(Path.GetTempPath(), "ft011byte-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tmp);
        try
        {
            var p1 = TypeScriptAppHostGenerator.EmitTo(tmp);
            var bytes1 = File.ReadAllBytes(p1);
            // Re-emit and re-read.
            var p2 = TypeScriptAppHostGenerator.EmitTo(tmp);
            Assert.Equal(p1, p2);
            var bytes2 = File.ReadAllBytes(p2);
            Assert.Equal(Sha256(bytes1), Sha256(bytes2));
        }
        finally
        {
            Directory.Delete(tmp, recursive: true);
        }
    }

    [Fact]
    public void I16_NoTimestampsOrMachinePathsOrTempDirsLeak()
    {
        var src = Source;
        Assert.DoesNotContain(Environment.MachineName, src);
        Assert.DoesNotContain(Path.GetTempPath(), src);
        Assert.DoesNotMatch(new Regex(@"\bos\.tmpdir\("), src);
        // No ISO-8601 timestamps.
        Assert.DoesNotMatch(new Regex(@"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}"), src);
    }

    // ---- J. No new error symbols --------------------------------------------------------

    [Fact]
    public void J17_NoErrorOrWarningSymbolLiteralsIntroduced()
    {
        var src = Source;
        // Look for stable-symbol shapes: E_FOO_BAR or W_FOO_BAR literal-looking tokens.
        Assert.DoesNotMatch(new Regex(@"\bE_[A-Z][A-Z0-9_]+"), src);
        Assert.DoesNotMatch(new Regex(@"\bW_[A-Z][A-Z0-9_]+"), src);
    }

    // ---- K. Recorded data targets the publisher slots ----------------------------------

    [Fact]
    public void K18_AllFourShims_WriteToTheSamePublisherSlotsObject()
    {
        var src = Source;
        // Each function writes through `attachOrGetSlots(builder)` — the single source of truth.
        foreach (var fn in new[] { "withCoolifyDeploy", "withImageRegistry", "withCoolifyDestination", "withManagedDashboard" })
        {
            var body = ExtractFunctionBody(src, fn);
            Assert.Contains("const slots = attachOrGetSlots(builder);", body);
        }
        // There is exactly one slot store; no parallel "TS-only" registration channel.
        Assert.Single(Regex.Matches(src, @"function attachOrGetSlots\("));
    }

    // ---- L. Ordering policy mirrors C# --------------------------------------------------

    [Fact]
    public void L19_OtherThreeShims_RequireWithCoolifyDeployFirst()
    {
        var src = Source;
        // Mirrors C# `InvalidOperationException` message ("requires a prior WithCoolifyDeploy(...) call").
        Assert.Contains("requireDeployPair('withImageRegistry', slots, 'FT-003');", src);
        Assert.Contains("requireDeployPair('withCoolifyDestination', slots, 'FT-005');", src);
        Assert.Contains("requireDeployPair('withManagedDashboard', slots, 'FT-010');", src);

        // And withCoolifyDeploy itself never calls requireDeployPair (it's the establishing call).
        var deploy = ExtractFunctionBody(src, "withCoolifyDeploy");
        Assert.DoesNotContain("requireDeployPair", deploy);
    }

    // ----- helpers ----------------------------------------------------------------------

    private static string ExtractFunctionBody(string src, string fnName)
    {
        var m = Regex.Match(src, @"export function " + Regex.Escape(fnName) + @"\b.*?\{(?<body>.*?)\n\}", RegexOptions.Singleline);
        Assert.True(m.Success, $"could not locate function '{fnName}' in emitted module");
        return m.Groups["body"].Value;
    }

    private static string Sha256(string s) => Sha256(Encoding.UTF8.GetBytes(s));
    private static string Sha256(byte[] bytes) => Convert.ToHexString(SHA256.HashData(bytes));
}
