using System.Text;

// Implements ADR-001: Aspire-graph to Coolify-hierarchy mapping (v1)
// Implements ADR-003: Imperative deploy orchestration with idempotent per-resource upserts (v1)
// Implements ADR-004: Coolify auth model — bearer token via Aspire secret parameters, per-instance (v1)
// Implements ADR-005: Image registry strategy — explicit publisher-push to a developer-chosen registry (v1)
namespace Aspire.Hosting.Coolify;

/// <summary>
/// FT-011: emits the TypeScript recording shim that mirrors the four C# publisher-configuration
/// extensions (<see cref="CoolifyBuilderExtensions.WithCoolifyDeploy"/>,
/// <see cref="CoolifyBuilderExtensions.WithImageRegistry"/>,
/// <see cref="CoolifyBuilderExtensions.WithCoolifyDestination"/>,
/// <see cref="CoolifyBuilderExtensions.WithManagedDashboard"/>) for TypeScript AppHosts.
/// <para>
/// The emitted module is a pure recording shim — it validates arguments and records handle
/// references into per-builder slots; it never reads a handle value, never talks to Coolify,
/// never builds an image, never runs a phase. The underlying .NET publisher drives every
/// behavioural concern regardless of authoring surface.
/// </para>
/// </summary>
public static class TypeScriptAppHostGenerator
{
    /// <summary>Conventional sub-directory under the AppHost project where the module lands.</summary>
    public const string GeneratedDirectoryName = "aspire.generated";

    /// <summary>Conventional file name for the emitted module.</summary>
    public const string GeneratedFileName = "coolify.ts";

    /// <summary>The first line of every emitted module — pinned for FT-011 I-9 byte-stability.</summary>
    public const string HeaderLine = "// auto-generated by aspire restore; do not edit";

    /// <summary>
    /// Returns the full source text of the emitted TypeScript module. The text is byte-stable
    /// for a given publisher version (FT-011 I-9): no timestamps, no machine-specific paths,
    /// no temp-dir derivations.
    /// </summary>
    public static string GetModuleSource()
    {
        var sb = new StringBuilder();
        sb.Append(HeaderLine).Append('\n');
        sb.Append("// FT-011 — TypeScript AppHost parity for the Coolify publisher.\n");
        sb.Append("// Recording shim only: argument validation + slot capture. The underlying .NET\n");
        sb.Append("// publisher (Aspire.Hosting.Coolify) drives every behavioural concern; this module\n");
        sb.Append("// never reads a handle value, never speaks HTTP, never composes image tags.\n");
        sb.Append("// Inherited rules: FT-001 (first-call-wins on deploy pair, token value never read),\n");
        sb.Append("// FT-003 (registry credentials travel as a pair, last-call-wins, never dereferenced),\n");
        sb.Append("// FT-005 (destination required, last-call-wins), FT-010 (managed dashboard opt-in,\n");
        sb.Append("// last-call-wins on handle, sticky opt-in flag).\n");
        sb.Append("//\n");
        sb.Append("// Ordering policy mirrors C# verbatim: calling withImageRegistry / withCoolifyDestination\n");
        sb.Append("// / withManagedDashboard before withCoolifyDeploy on the same builder throws the same\n");
        sb.Append("// precise message the C# extensions throw via InvalidOperationException.\n");
        sb.Append('\n');
        sb.Append("export interface ParameterResource { readonly name: string; }\n");
        sb.Append("export interface IResourceHandle<T> { readonly resource: T; }\n");
        sb.Append("export interface IDistributedApplicationBuilder {\n");
        sb.Append("  __coolifyPublisherSlots?: CoolifyPublisherSlots;\n");
        sb.Append("}\n");
        sb.Append('\n');
        sb.Append("export interface CoolifyPublisherSlots {\n");
        sb.Append("  deployPair?: [IResourceHandle<ParameterResource>, IResourceHandle<ParameterResource>];\n");
        sb.Append("  registryPrefix?: IResourceHandle<ParameterResource>;\n");
        sb.Append("  registryUsername?: IResourceHandle<ParameterResource> | null;\n");
        sb.Append("  registryPassword?: IResourceHandle<ParameterResource> | null;\n");
        sb.Append("  destinationName?: IResourceHandle<ParameterResource>;\n");
        sb.Append("  dashboardToken?: IResourceHandle<ParameterResource>;\n");
        sb.Append("  dashboardOptedIn?: boolean;\n");
        sb.Append("}\n");
        sb.Append('\n');
        sb.Append("function attachOrGetSlots(builder: IDistributedApplicationBuilder): CoolifyPublisherSlots {\n");
        sb.Append("  if (!builder.__coolifyPublisherSlots) {\n");
        sb.Append("    builder.__coolifyPublisherSlots = {};\n");
        sb.Append("  }\n");
        sb.Append("  return builder.__coolifyPublisherSlots;\n");
        sb.Append("}\n");
        sb.Append('\n');
        sb.Append("function requireDeployPair(fnName: string, slots: CoolifyPublisherSlots, see: string): void {\n");
        sb.Append("  if (slots.deployPair === undefined) {\n");
        sb.Append("    throw new Error(fnName + ' requires a prior withCoolifyDeploy(...) call on the same builder. See ' + see + '.');\n");
        sb.Append("  }\n");
        sb.Append("}\n");
        sb.Append('\n');

        // withCoolifyDeploy
        sb.Append("export function withCoolifyDeploy(\n");
        sb.Append("  builder: IDistributedApplicationBuilder,\n");
        sb.Append("  url: IResourceHandle<ParameterResource>,\n");
        sb.Append("  token: IResourceHandle<ParameterResource>,\n");
        sb.Append("): IDistributedApplicationBuilder {\n");
        sb.Append("  if (builder === null || builder === undefined) {\n");
        sb.Append("    throw new Error(\"withCoolifyDeploy: 'builder' argument must be an IDistributedApplicationBuilder; got \" + String(builder) + \". See FT-001.\");\n");
        sb.Append("  }\n");
        sb.Append("  if (url === null || url === undefined) {\n");
        sb.Append("    throw new Error(\"withCoolifyDeploy: 'url' argument must be a parameter handle; got \" + String(url) + \". See FT-001.\");\n");
        sb.Append("  }\n");
        sb.Append("  if (token === null || token === undefined) {\n");
        sb.Append("    throw new Error(\"withCoolifyDeploy: 'token' argument must be a parameter handle; got \" + String(token) + \". See FT-001.\");\n");
        sb.Append("  }\n");
        sb.Append("  const slots = attachOrGetSlots(builder);\n");
        sb.Append("  // FT-001 I-4: first-call-wins. Second call with any pair is a silent no-op.\n");
        sb.Append("  if (slots.deployPair !== undefined) {\n");
        sb.Append("    return builder;\n");
        sb.Append("  }\n");
        sb.Append("  slots.deployPair = [url, token];\n");
        sb.Append("  return builder;\n");
        sb.Append("}\n");
        sb.Append('\n');

        // withImageRegistry
        sb.Append("export function withImageRegistry(\n");
        sb.Append("  builder: IDistributedApplicationBuilder,\n");
        sb.Append("  prefix: IResourceHandle<ParameterResource>,\n");
        sb.Append("  credentials?: [IResourceHandle<ParameterResource>, IResourceHandle<ParameterResource>],\n");
        sb.Append("): IDistributedApplicationBuilder {\n");
        sb.Append("  if (builder === null || builder === undefined) {\n");
        sb.Append("    throw new Error(\"withImageRegistry: 'builder' argument must be an IDistributedApplicationBuilder; got \" + String(builder) + \". See FT-003.\");\n");
        sb.Append("  }\n");
        sb.Append("  if (prefix === null || prefix === undefined) {\n");
        sb.Append("    throw new Error(\"withImageRegistry: 'prefix' argument must be a parameter handle; got \" + String(prefix) + \". See FT-003.\");\n");
        sb.Append("  }\n");
        sb.Append("  let user: IResourceHandle<ParameterResource> | null = null;\n");
        sb.Append("  let pass: IResourceHandle<ParameterResource> | null = null;\n");
        sb.Append("  if (credentials !== undefined && credentials !== null) {\n");
        sb.Append("    if (credentials[0] === null || credentials[0] === undefined) {\n");
        sb.Append("      throw new Error(\"withImageRegistry: 'credentials[0]' (username) must be a parameter handle; got \" + String(credentials[0]) + \". See FT-003.\");\n");
        sb.Append("    }\n");
        sb.Append("    if (credentials[1] === null || credentials[1] === undefined) {\n");
        sb.Append("      throw new Error(\"withImageRegistry: 'credentials[1]' (password) must be a parameter handle; got \" + String(credentials[1]) + \". See FT-003.\");\n");
        sb.Append("    }\n");
        sb.Append("    user = credentials[0];\n");
        sb.Append("    pass = credentials[1];\n");
        sb.Append("  }\n");
        sb.Append("  const slots = attachOrGetSlots(builder);\n");
        sb.Append("  requireDeployPair('withImageRegistry', slots, 'FT-003');\n");
        sb.Append("  // FT-003 I-8: last-call-wins on the (prefix, user, pass) triple.\n");
        sb.Append("  slots.registryPrefix = prefix;\n");
        sb.Append("  slots.registryUsername = user;\n");
        sb.Append("  slots.registryPassword = pass;\n");
        sb.Append("  return builder;\n");
        sb.Append("}\n");
        sb.Append('\n');

        // withCoolifyDestination
        sb.Append("export function withCoolifyDestination(\n");
        sb.Append("  builder: IDistributedApplicationBuilder,\n");
        sb.Append("  name: IResourceHandle<ParameterResource>,\n");
        sb.Append("): IDistributedApplicationBuilder {\n");
        sb.Append("  if (builder === null || builder === undefined) {\n");
        sb.Append("    throw new Error(\"withCoolifyDestination: 'builder' argument must be an IDistributedApplicationBuilder; got \" + String(builder) + \". See FT-005.\");\n");
        sb.Append("  }\n");
        sb.Append("  if (name === null || name === undefined) {\n");
        sb.Append("    throw new Error(\"withCoolifyDestination: 'name' argument must be a parameter handle; got \" + String(name) + \". See FT-005.\");\n");
        sb.Append("  }\n");
        sb.Append("  const slots = attachOrGetSlots(builder);\n");
        sb.Append("  requireDeployPair('withCoolifyDestination', slots, 'FT-005');\n");
        sb.Append("  // FT-005 §0: last-call-wins on the destination handle.\n");
        sb.Append("  slots.destinationName = name;\n");
        sb.Append("  return builder;\n");
        sb.Append("}\n");
        sb.Append('\n');

        // withManagedDashboard
        sb.Append("export function withManagedDashboard(\n");
        sb.Append("  builder: IDistributedApplicationBuilder,\n");
        sb.Append("  dashboardToken: IResourceHandle<ParameterResource>,\n");
        sb.Append("): IDistributedApplicationBuilder {\n");
        sb.Append("  if (builder === null || builder === undefined) {\n");
        sb.Append("    throw new Error(\"withManagedDashboard: 'builder' argument must be an IDistributedApplicationBuilder; got \" + String(builder) + \". See FT-010.\");\n");
        sb.Append("  }\n");
        sb.Append("  if (dashboardToken === null || dashboardToken === undefined) {\n");
        sb.Append("    throw new Error(\"withManagedDashboard: 'dashboardToken' argument must be a parameter handle; got \" + String(dashboardToken) + \". See FT-010.\");\n");
        sb.Append("  }\n");
        sb.Append("  const slots = attachOrGetSlots(builder);\n");
        sb.Append("  requireDeployPair('withManagedDashboard', slots, 'FT-010');\n");
        sb.Append("  // FT-010 I-5: last-call-wins on the handle; opt-in flag stays true once set.\n");
        sb.Append("  slots.dashboardToken = dashboardToken;\n");
        sb.Append("  slots.dashboardOptedIn = true;\n");
        sb.Append("  return builder;\n");
        sb.Append("}\n");

        return sb.ToString();
    }

    /// <summary>
    /// Emits the TypeScript module under <c>&lt;projectDirectory&gt;/aspire.generated/coolify.ts</c>,
    /// writing nowhere else (FT-011 I-10). Uses temp-then-rename for atomic replacement
    /// (FT-011 §"Error handling": generator hook is atomic per emitted file).
    /// </summary>
    /// <returns>The absolute path of the emitted module file.</returns>
    public static string EmitTo(string projectDirectory)
    {
        ArgumentNullException.ThrowIfNull(projectDirectory);
        var dir = Path.Combine(projectDirectory, GeneratedDirectoryName);
        Directory.CreateDirectory(dir);
        var path = Path.Combine(dir, GeneratedFileName);
        var tmp = path + ".tmp";
        File.WriteAllText(tmp, GetModuleSource());
        if (File.Exists(path))
        {
            File.Delete(path);
        }
        File.Move(tmp, path);
        return path;
    }
}
